/* XPM */
static char * scalePlus [] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s foreground	m white	c white",
"X	s topShadowColor	m white	c #c8c8c8c8c8c8",
"o	s selectColor	m white	c #7d7d7d7d7d7d",
"O	s bottomShadowColor	m black	c #646464646464",
"+	s iconColor8	m black	c magenta",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"             .X  oX             ",
"            .XO  oXO            ",
"           .X+O  oX+O           ",
"          .X++O  oX++O          ",
"         .X+++O  oX+++O         ",
"        .X++++O  oX++++O        ",
"       .X+++++O  oX+++++O       ",
"      .X++++++O  oX++++++O      ",
"     .X+++++++O  oX+++++++O     ",
"    .X++++++++O  oX++++++OOO    ",
"     OO+++++++O  oX+++++OOO     ",
"      OO++++++O  oX++++OOO      ",
"       OO+++++O  oX+++OOO       ",
"        OO++++O  oX++OOO        ",
"         OO+++O  oX+OOO         ",
"          OO++O  oOOOO          ",
"           OOOO  oOOO           ",
"            OOO  OOO            ",
"             OO  OO             ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
